### ISSUE TITLE
WCNSS_qcom_cfg.ini update and Wi-Fi performance

### ISSUE THREAD

**Issue by HanabishiRecca** [LineageOS/android_device_sony_nile-common#3]
This **WCNSS_qcom_cfg.ini** update here https://github.com/LineageOS/android_device_sony_nile-common/commit/e7ce197a6eee3a7cbc57779839356cdde3255b23 kills Wi-Fi performance for me. Signal level becomes very low and 2.4 GHz speed mode always stuck maximum at 26 mbit.
When I replacing this file with old one (before update version) all becomes ok - good signal and 72 mbit speed.

**Comment by luk1337** [comment]
Try to find which exact change breaks it.

**Comment by luk1337** [comment]
Can't say that i'm able to repro it. 2.4GHz sucks even with the revert but I pushed 90b6d0d1ea47971919c137a6588c313e47ee5b3e which at the very least makes it bit more usable.

**Comment by HanabishiRecca** [comment]
@luk1337 I'm now trying to figure out which param exactly affects it.

By the way dual bonding is a cool thing, I've used such patch manually before. But this is not the solution. With dual bonding situation still similar:
New file: 54 mbit mode
Old file: 150 mbit mode (maximum for 2.4)

And looks like 5 Ghz also affected.

**Comment by luk1337** [comment]
5GHz works perfectly here. Also settings always show 72/150 here so that was never an issue here.

**Comment by HanabishiRecca** [comment]
Hmm, have no luck with parameter search. But now phone completely stuck at 54 mbps mode (like it operates in 11g) and even old file doesn't help anymore :neutral_face:

**Comment by luk1337** [comment]
rip

**Comment by HanabishiRecca** [comment]
Router reports a very strange thing
![img](https://user-images.githubusercontent.com/13597663/67493983-f6093480-f691-11e9-815f-5cdedbcc06fb.png)
Like 54 stuck only in one direction

**Comment by luk1337** [comment]
![image](https://user-images.githubusercontent.com/6830979/67494626-cb12e680-f679-11e9-9bab-895ac8845ac9.png)

**Comment by luk1337** [comment]
Also same on 5GHz
![image](https://user-images.githubusercontent.com/6830979/67494741-044b5680-f67a-11e9-92fc-5d3fdc920fa8.png)

**Comment by HanabishiRecca** [comment]
Luckly 5GHz kinda ok
![img](https://user-images.githubusercontent.com/13597663/67495082-c3603b80-f693-11e9-9cf4-58d290e399f5.png)

**Comment by luk1337** [comment]
BTW are you on 16.0 or 17.0?

**Comment by HanabishiRecca** [comment]
16 official builds

**Comment by luk1337** [comment]
kk then it shouldn't be a problem.

**Comment by HanabishiRecca** [comment]
I've done some additional tests with other devices and even another router. And now I'm sure this is phone issue. Problem suddenly appeared after one of a previous updates.
Also 5 GHz signal is very poor. On the last screenshot above it has 80% while lying directly on the router. Signal becomes unusable farther than 5-6 meters even in direct sight.

**Comment by luk1337** [comment]
@HanabishiRecca what baseband are you on?

**Comment by HanabishiRecca** [comment]
@luk1337 basband of gsm?
Btw I've read a post about updating to new FW. I will try to update system partitions (bluetooth, dsp, modem etc.).

**Comment by luk1337** [comment]
Yes, that's the only baseband version you can see anyway.
If it's 2018xxxx then it's 50.1, if 2019xxxx then it's 50.2.
If you're on 50.1 one you should try flashing my 50.2 pkg from XDA post.

**Comment by luk1337** [comment]
btw if you use irc you may consider just hanging out on #titandev @ freenode, it's probably the best way to contact me..

**Comment by HanabishiRecca** [comment]
@luk1337 2018, I'm not updated system FW very long ago.

**Comment by HanabishiRecca** [comment]
@luk1337, yay, flashing the package helped! Thanks a lot!

So, problem was caused by old FW, closing the issue.
